services:
  db:
    env_file: .env
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DOCKER_COMPOSE_SERVICE_NAME=${POSTGRES_DOCKER_COMPOSE_SERVICE_NAME}
    image: alexshyshko_task-2-image_${POSTGRES_DOCKER_COMPOSE_SERVICE_NAME}
    build:
      context: .
      dockerfile: db.Dockerfile
    container_name: alexshyshko_task-2-container_${POSTGRES_DOCKER_COMPOSE_SERVICE_NAME}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend
    command: ["postgres", "-p", "${POSTGRES_PORT}"]
  prod:
    env_file: .env
    environment:
      - PORT=${PORT}
      - DB_TYPE=postgres
      - DB_HOST=${POSTGRES_DOCKER_COMPOSE_SERVICE_NAME}
      - DB_PORT=${POSTGRES_PORT}
      - DB_USERNAME=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_DATABASE=${POSTGRES_DB}
    image: alexshyshko_task-2-image_prod
    build:
      context: .
      dockerfile: prod.Dockerfile
      target: prod
    container_name: alexshyshko_task-2-container_prod
    ports:
      - "${PORT}:${PORT}"
    restart: unless-stopped
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - backend
    depends_on:
      db:
        condition: service_started
    command: npm run start:docker

volumes:
  pgdata:

networks:
  backend:
    driver: bridge