services:
  dev:
    env_file: .env
    image: alexshyshko_task-2-image_dev
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    container_name: alexshyshko_task-2-container_dev
    ports:
      - "${PORT}:${PORT}"
    restart: unless-stopped
    volumes:
      - .:/app
    working_dir: /app
    command: ["npm", "run", "start:dev"]
  prod:
    env_file: .env
    image: alexshyshko_task-2-image_prod
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    container_name: alexshyshko_task-2-container_prod
    ports:
      - "${PORT}:${PORT}"
    restart: unless-stopped
    # volumes:
    #   - .:/app
    working_dir: /app
    command: ["npm", "run", "start:prod"]