services:
  db:
    env_file: .env
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_PORT=${DATABASE_PORT}
    image: alexshyshko_task-2-image_db
    build:
      context: .
      dockerfile: db.Dockerfile
    container_name: alexshyshko_task-2-container_db
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network
    working_dir: /app
    command: ["postgres", "-p", "${DATABASE_PORT}"]
  prod:
    env_file: .env
    image: alexshyshko_task-2-image_prod
    build:
      context: .
      dockerfile: prod.Dockerfile
      target: prod
    container_name: alexshyshko_task-2-container_prod
    ports:
      - "${PORT}:${PORT}"
    restart: unless-stopped
    volumes:
      - ./src:/app/src
    networks:
      - app-network
    working_dir: /app
    depends_on:
      - db

volumes:
  pgdata:

networks:
  app-network:
    driver: bridge